language: rust
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - libibverbs1
    - ninja-build
    - libnl-3-dev
    - libnl-genl-3-dev
    - libnl-route-3-dev
    - libudev-dev
    - cmake
    - cmake-data
    - gcc-5
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake 3.2.3
env:
  - LLVM_VERSION=3.9.0
rust:
  - nightly
  - beta
  - stable
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
